{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface.doc",
    "module": "designsystem",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface.doc",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0.aar",
          "url": "designsystem-1.0.0.aar",
          "size": 2062330,
          "sha512": "8d03ee7657b3288066e8ea1a6afd431be0e2b26075eaa93a0ed9282704b1773e9de5149555adb4ef3700323a117b123d9150506f3798c1ed5e41ebf3d25fd523",
          "sha256": "a2ea60db8d8d9d0534940823c295003cd39a39b24e763108cd8270ce79856bc8",
          "sha1": "943e32c5ebc401c29942de2d5c413db898cb68dc",
          "md5": "6d4292a9e4391979d8782e2bff8afc90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0.aar",
          "url": "designsystem-1.0.0.aar",
          "size": 2062330,
          "sha512": "8d03ee7657b3288066e8ea1a6afd431be0e2b26075eaa93a0ed9282704b1773e9de5149555adb4ef3700323a117b123d9150506f3798c1ed5e41ebf3d25fd523",
          "sha256": "a2ea60db8d8d9d0534940823c295003cd39a39b24e763108cd8270ce79856bc8",
          "sha1": "943e32c5ebc401c29942de2d5c413db898cb68dc",
          "md5": "6d4292a9e4391979d8782e2bff8afc90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.0.0-sources.jar",
          "url": "designsystem-1.0.0-sources.jar",
          "size": 67950,
          "sha512": "11e31b74703d84edb01c17941dc467e58bc11dfd5780bd32e61cd5adbab4dbdecacd9146d480617b66dd7acf5e28b3ee56a30ac40604edc00e2d9332a4e2c9d9",
          "sha256": "e5952471f4584148d7cf00b6fe1b281b896291caaa8c7dec5593a44c7ff9500a",
          "sha1": "b321757dfba19e532a855179c3cb1ee7432419f0",
          "md5": "f2af873c8482a4d4e98ab750eb98ef79"
        }
      ]
    }
  ]
}
