{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface.doc",
    "module": "domain",
    "version": "1.0.1-snapshot-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface.doc",
          "module": "designsystem",
          "version": {
            "requires": "1.0.1-snapshot-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.1-snapshot-1.aar",
          "url": "domain-1.0.1-snapshot-1.aar",
          "size": 43547,
          "sha512": "7c8af003a5f9991b39968102dd6221c8a0ed43b74f7d448f009ae0feb5b61f07a84e80296dec69fc637a6bb51e7d969bb44f5dd144c5693e0cec9ef64db2bf66",
          "sha256": "1928e97d1c9075e6590168cb785caaeba519b93268a7c32e91371a64a3334411",
          "sha1": "29ec002b22bab25311c0c9c635fade2a481dedad",
          "md5": "9f30be191564adc25b4c6d71ca1e63c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "br.com.certiface.doc",
          "module": "designsystem",
          "version": {
            "requires": "1.0.1-snapshot-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.1-snapshot-1.aar",
          "url": "domain-1.0.1-snapshot-1.aar",
          "size": 43547,
          "sha512": "7c8af003a5f9991b39968102dd6221c8a0ed43b74f7d448f009ae0feb5b61f07a84e80296dec69fc637a6bb51e7d969bb44f5dd144c5693e0cec9ef64db2bf66",
          "sha256": "1928e97d1c9075e6590168cb785caaeba519b93268a7c32e91371a64a3334411",
          "sha1": "29ec002b22bab25311c0c9c635fade2a481dedad",
          "md5": "9f30be191564adc25b4c6d71ca1e63c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.0.1-snapshot-1-sources.jar",
          "url": "domain-1.0.1-snapshot-1-sources.jar",
          "size": 11135,
          "sha512": "9a07d0713a45d3aa6996cab71aaff16a79004fe783b9aeaa64718309690259b62c9febf6131c11bd7155fd09a50171783de361f34c92da32716fe28e1f82fe50",
          "sha256": "4ebbae2d6ee691852bb41d7a2707530d1bffb126819aadc0430b7eb48efe8280",
          "sha1": "cd9c0046076ffe7f3d41d6a6d51904b1bd8af00a",
          "md5": "087e22f846c6bd0d9f4e9fc757a0fd8e"
        }
      ]
    }
  ]
}
