{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "designsystem",
    "version": "1.0.0-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-2.aar",
          "url": "designsystem-1.0.0-snapshot-2.aar",
          "size": 2044757,
          "sha512": "4ea81bfa2a663fe3a7f0f36657f5a0ef46e2ac975d2190d7bd0115a41e94b88d61e51ce9f4cb5288ea2dcfbba5db0175996f7bab325b73930a2fa405e53da1e6",
          "sha256": "995b9e905edab8de78c4ce01b0882a8ed92d1922fd90957a79fee2c6c5143113",
          "sha1": "02339df347db7ecefb4146b912775aef9555a997",
          "md5": "3708b8201e2f12fee9aba8c594f88d64"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-2.aar",
          "url": "designsystem-1.0.0-snapshot-2.aar",
          "size": 2044757,
          "sha512": "4ea81bfa2a663fe3a7f0f36657f5a0ef46e2ac975d2190d7bd0115a41e94b88d61e51ce9f4cb5288ea2dcfbba5db0175996f7bab325b73930a2fa405e53da1e6",
          "sha256": "995b9e905edab8de78c4ce01b0882a8ed92d1922fd90957a79fee2c6c5143113",
          "sha1": "02339df347db7ecefb4146b912775aef9555a997",
          "md5": "3708b8201e2f12fee9aba8c594f88d64"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-2-sources.jar",
          "url": "designsystem-1.0.0-snapshot-2-sources.jar",
          "size": 64546,
          "sha512": "d4a242e68ecddb3275f62f072dc01e90e0eb78887f568b69749542d9203d7b5c1f32396f9a69235f1f0d361f00c142fd67bfde094de254800dfcf3fadaa477b0",
          "sha256": "ec1f077d62ec2219c6d2ce648c415320b9143c2bcbc34102a8fe5a96677efd5b",
          "sha1": "f85052bc775101456bdaf8e3d99de70a596061d0",
          "md5": "7a581964da6295e05162fb9738371775"
        }
      ]
    }
  ]
}
