{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "designsystem",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-0.0.2.aar",
          "url": "designsystem-0.0.2.aar",
          "size": 2168177,
          "sha512": "838b05a15945f5c9cc0a5fb72677ed9c6a612ac6558c9369746baac0f2d232691db9b7b4fb83f84c52c1ae2c8735776160ad863ed8c57c6d8a0e61c3ffd094fe",
          "sha256": "2820e6961dbe3c00d16c43bd7b09669bcc9e580af5defb262714364901c5cd17",
          "sha1": "be0c55dbb188ff29eb097c1d41cfedc1407247ff",
          "md5": "0a2bbefedb85ac734f90ca76a53e186f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-0.0.2.aar",
          "url": "designsystem-0.0.2.aar",
          "size": 2168177,
          "sha512": "838b05a15945f5c9cc0a5fb72677ed9c6a612ac6558c9369746baac0f2d232691db9b7b4fb83f84c52c1ae2c8735776160ad863ed8c57c6d8a0e61c3ffd094fe",
          "sha256": "2820e6961dbe3c00d16c43bd7b09669bcc9e580af5defb262714364901c5cd17",
          "sha1": "be0c55dbb188ff29eb097c1d41cfedc1407247ff",
          "md5": "0a2bbefedb85ac734f90ca76a53e186f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "designsystem-0.0.2-sources.jar",
          "url": "designsystem-0.0.2-sources.jar",
          "size": 138255,
          "sha512": "a43e2d9b98f725927f2ab9b49bd02bc8f8492fb57cdae95b0b535049b489e9062e4bd37c32594b55d3325c732b3fe405287eb99b6fb6ef9c44406eb15551683d",
          "sha256": "c28c6d57b4f9de2010210490f51be56a5bf541da959ba06e5114e3267f2aad72",
          "sha1": "0ed3f286f1869e69510b7ffe4343ff75615a3ccb",
          "md5": "09f57534931583dab94406a232b93254"
        }
      ]
    }
  ]
}
