{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface.doc",
    "module": "network",
    "version": "1.0.1-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface.doc",
          "module": "core",
          "version": {
            "requires": "1.0.1-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "domain",
          "version": {
            "requires": "1.0.1-snapshot-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-1.0.1-snapshot-2.aar",
          "url": "network-1.0.1-snapshot-2.aar",
          "size": 27789,
          "sha512": "5893cbd1d18470b223ae16d0cb083bed68bb183dda799d6a6ce1d625aa32caa0657b5bf00dbb155dd805a91261f15dc121abc6328e0e6866df7aa5bbe42ba0db",
          "sha256": "ec006228937f558def473cfdc86c131636478f0271713a07eb667a6aa99034e8",
          "sha1": "abd0bfbc13dbb5fe56a303e91b42ed42e154a664",
          "md5": "439cbeb626999913c646a384dc318ae7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "core",
          "version": {
            "requires": "1.0.1-snapshot-2"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "domain",
          "version": {
            "requires": "1.0.1-snapshot-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-1.0.1-snapshot-2.aar",
          "url": "network-1.0.1-snapshot-2.aar",
          "size": 27789,
          "sha512": "5893cbd1d18470b223ae16d0cb083bed68bb183dda799d6a6ce1d625aa32caa0657b5bf00dbb155dd805a91261f15dc121abc6328e0e6866df7aa5bbe42ba0db",
          "sha256": "ec006228937f558def473cfdc86c131636478f0271713a07eb667a6aa99034e8",
          "sha1": "abd0bfbc13dbb5fe56a303e91b42ed42e154a664",
          "md5": "439cbeb626999913c646a384dc318ae7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "network-1.0.1-snapshot-2-sources.jar",
          "url": "network-1.0.1-snapshot-2-sources.jar",
          "size": 13582,
          "sha512": "a3d6b302b078daad653631a92176dfe8139b3a6729f6d9c572aaf18bc96ac99afd40c307f5726e6dd578dc74f195e541cc4887d7fc1fc125cb3bf610fcf8a952",
          "sha256": "e95bea6b5be5ab09766bda42a5e09455196e3f6086949c68bfbe52e873331e0c",
          "sha1": "3bf630b2db19dc9270d5d2c8c3dd0fa1eb84506f",
          "md5": "c179fca0a9a3d728b8aa0dbaf605b89a"
        }
      ]
    }
  ]
}
