{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "designsystem",
    "version": "1.0.0-snapshot-5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-5.aar",
          "url": "designsystem-1.0.0-snapshot-5.aar",
          "size": 2058470,
          "sha512": "8d54c16ea13824a180d7904d0dc8d5410bd81e52f79f72df44ba7dbf4aa96a512f5c9f12c4603e29e8534536eb26579ebd2a9b67e40d3df7bfdebec7250fe2c0",
          "sha256": "19e7fef0e9330b9ca7acf3b34c056fa80f3c84c3e737f9d5ee26c53c7e5fa858",
          "sha1": "a2fdb86ab0005aa4920538a7cb36ae968d7c34ad",
          "md5": "63351f6c2854e496a5ae673084e44096"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-5.aar",
          "url": "designsystem-1.0.0-snapshot-5.aar",
          "size": 2058470,
          "sha512": "8d54c16ea13824a180d7904d0dc8d5410bd81e52f79f72df44ba7dbf4aa96a512f5c9f12c4603e29e8534536eb26579ebd2a9b67e40d3df7bfdebec7250fe2c0",
          "sha256": "19e7fef0e9330b9ca7acf3b34c056fa80f3c84c3e737f9d5ee26c53c7e5fa858",
          "sha1": "a2fdb86ab0005aa4920538a7cb36ae968d7c34ad",
          "md5": "63351f6c2854e496a5ae673084e44096"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-5-sources.jar",
          "url": "designsystem-1.0.0-snapshot-5-sources.jar",
          "size": 67586,
          "sha512": "1dfe369054f1c9f3b6bf3eedfc0b722178c8b739439d7669ba96dbf8943a2734a83679df8af823322c34de1fe508a413b4b85f86eab39bf6f7104e8532f3f5ce",
          "sha256": "0c470793bf23f573688ff115e01d850cb095bf014aa3acd6ca13909730ab9f46",
          "sha1": "374461271d010ab329c9b742ab4c672711dc4dea",
          "md5": "d7704a3e6aabbccccfb524b2d290e92c"
        }
      ]
    }
  ]
}
