{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "designsystem",
    "version": "1.0.0-snapshot-6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-6.aar",
          "url": "designsystem-1.0.0-snapshot-6.aar",
          "size": 2062316,
          "sha512": "4e21705ba59845322b78ff6b46e454bfd7fbcb87782bf0727453cfa6c93df223a253be7205063bf2ad93826ed8dc434030ab43c6595c901a61023800a814a855",
          "sha256": "e032017ddccc16c3af44345fd72e9d1d7e724f3144571c9db85a2c44b83c2baa",
          "sha1": "b9ff6bb36642e5035e8014ac839320981a81866e",
          "md5": "7be424e924477e3452d5d60b272312d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-6.aar",
          "url": "designsystem-1.0.0-snapshot-6.aar",
          "size": 2062316,
          "sha512": "4e21705ba59845322b78ff6b46e454bfd7fbcb87782bf0727453cfa6c93df223a253be7205063bf2ad93826ed8dc434030ab43c6595c901a61023800a814a855",
          "sha256": "e032017ddccc16c3af44345fd72e9d1d7e724f3144571c9db85a2c44b83c2baa",
          "sha1": "b9ff6bb36642e5035e8014ac839320981a81866e",
          "md5": "7be424e924477e3452d5d60b272312d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-6-sources.jar",
          "url": "designsystem-1.0.0-snapshot-6-sources.jar",
          "size": 67948,
          "sha512": "2c822ee47a84c902f8a0b59c45d474d6b190e717802eb05f9c74396bdbfcfaeb52aefc17992d7ac1fb805429c8834fae3b994176324289fea0083d77545d9a02",
          "sha256": "50b80b8ee59e5091accf76734430d96465af2e27da56928f85bb072a28f478bd",
          "sha1": "4db8e097c9428c95501dd315a73a5292b66df8cb",
          "md5": "27dbb101e73073b79137c89d429e0f52"
        }
      ]
    }
  ]
}
