{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface.doc",
    "module": "multimedia",
    "version": "1.0.1-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "multimedia-1.0.1-snapshot-2.aar",
          "url": "multimedia-1.0.1-snapshot-2.aar",
          "size": 48752,
          "sha512": "b4f5db21b17283af72b8c64d7bce5cca413cf96c69deac26e7b953f4476565b13e41132e842b36462b92e0609196c78c153b14904256b4b68938c87b2ad70b25",
          "sha256": "a76e9cb1523e1482bc0ab8312240feac5b353b54b42c85bdc6ec8643b1217699",
          "sha1": "0396e0c7f5cfe738fd1a665b50bca4fd6061edd6",
          "md5": "5e289bebadc80e930e58da29741c3478"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "multimedia-1.0.1-snapshot-2.aar",
          "url": "multimedia-1.0.1-snapshot-2.aar",
          "size": 48752,
          "sha512": "b4f5db21b17283af72b8c64d7bce5cca413cf96c69deac26e7b953f4476565b13e41132e842b36462b92e0609196c78c153b14904256b4b68938c87b2ad70b25",
          "sha256": "a76e9cb1523e1482bc0ab8312240feac5b353b54b42c85bdc6ec8643b1217699",
          "sha1": "0396e0c7f5cfe738fd1a665b50bca4fd6061edd6",
          "md5": "5e289bebadc80e930e58da29741c3478"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multimedia-1.0.1-snapshot-2-sources.jar",
          "url": "multimedia-1.0.1-snapshot-2-sources.jar",
          "size": 17241,
          "sha512": "6b36363d4922ed6e61e682188d9b309020452d1cb53612949b8f47756c25013452bf0fa40a066086e13fd1a1d0a1076e833d095015dd75781fc0848590480be1",
          "sha256": "c88be83b815a4277cab015465f29627f786b43918cf65be4a75d9adc984ab7ab",
          "sha1": "d928069759f0c9a1d19ee63f7f7fde0ed8316955",
          "md5": "ef4c05888707080f75184dd8d1e22a2d"
        }
      ]
    }
  ]
}
