{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface.doc",
    "module": "logging",
    "version": "1.0.2-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.2-snapshot.aar",
          "url": "logging-1.0.2-snapshot.aar",
          "size": 65655,
          "sha512": "cb154c702fe697593b268991c14c9358d410ac428bbe6a57b689613571a0314892aa9423217c4fdf3128c4ebb068fc7c4706bb7c6ca973c4b1b326a424ea96b8",
          "sha256": "e2ee2190ef0e9ca99c95c21e7407dfaf376244f85f1714c7b2e07c5924e3beab",
          "sha1": "34ccd61bf6ecf79986692262ff9e56b74c85aa39",
          "md5": "65f5da86919cea312ce5f27982e116e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "domain",
          "version": {
            "requires": "1.0.2-snapshot"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "utils",
          "version": {
            "requires": "1.0.2-snapshot"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "core",
          "version": {
            "requires": "1.0.2-snapshot"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.2-snapshot.aar",
          "url": "logging-1.0.2-snapshot.aar",
          "size": 65655,
          "sha512": "cb154c702fe697593b268991c14c9358d410ac428bbe6a57b689613571a0314892aa9423217c4fdf3128c4ebb068fc7c4706bb7c6ca973c4b1b326a424ea96b8",
          "sha256": "e2ee2190ef0e9ca99c95c21e7407dfaf376244f85f1714c7b2e07c5924e3beab",
          "sha1": "34ccd61bf6ecf79986692262ff9e56b74c85aa39",
          "md5": "65f5da86919cea312ce5f27982e116e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-1.0.2-snapshot-sources.jar",
          "url": "logging-1.0.2-snapshot-sources.jar",
          "size": 27196,
          "sha512": "9962972042d628bc20ba71200ee9eeaa469b09d2ea61f2670baf91cb913a29deb01876ba0ebaf6ca07ffdcfb6939a04f1fca6f80550399da90219f41fa927848",
          "sha256": "b7c9c8529f62c764605b85d263ddf2d808f6fd0fc1fda7133de1481f71ae06b4",
          "sha1": "725573f3df331e5b6cf9e9c2b2546a931b0a3848",
          "md5": "0215c48d7b162f50c0693b439d1e920f"
        }
      ]
    }
  ]
}
