{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "multimedia",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "multimedia-0.0.1.aar",
          "url": "multimedia-0.0.1.aar",
          "size": 67916,
          "sha512": "68d7bdc2f702e685536768fe22308ec559e32b87a8d50ea2b9df8e0cd4ea7d2a76e26f793f7f8f0fc3a4f141f00a46dc48cdf41a2124d4a980fcf4d1ad54df39",
          "sha256": "fdd29c7d8e8acdf98b63988c825840c28fccda772f4b954c072c027455197fa3",
          "sha1": "184bab15ac9aad40a53dc287ff69d427ed849159",
          "md5": "93eb3277252d21d501848dfbcabc640c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "multimedia-0.0.1.aar",
          "url": "multimedia-0.0.1.aar",
          "size": 67916,
          "sha512": "68d7bdc2f702e685536768fe22308ec559e32b87a8d50ea2b9df8e0cd4ea7d2a76e26f793f7f8f0fc3a4f141f00a46dc48cdf41a2124d4a980fcf4d1ad54df39",
          "sha256": "fdd29c7d8e8acdf98b63988c825840c28fccda772f4b954c072c027455197fa3",
          "sha1": "184bab15ac9aad40a53dc287ff69d427ed849159",
          "md5": "93eb3277252d21d501848dfbcabc640c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "multimedia-0.0.1-sources.jar",
          "url": "multimedia-0.0.1-sources.jar",
          "size": 48401,
          "sha512": "2f53ee40aace430eb537a0829dda1c4bb877a7fddab2c358e814e09dd67d46cea517bb974f5e610dd16de1f23851fcfe231a18fb4fbd5d75ad1a950abfb3badd",
          "sha256": "51fd0274abffe11ca08cf1450bc30983537bdee4a235ad4c6c7279cce8a9102d",
          "sha1": "65f4f0e82f078fc9e329c296972ae9c921fa5230",
          "md5": "3d997f17bf19183f0c770b8775eaea80"
        }
      ]
    }
  ]
}
