{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "designsystem",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-0.0.4.aar",
          "url": "designsystem-0.0.4.aar",
          "size": 2219307,
          "sha512": "b54fce52d9f7bb9d72f8ed1e0ffcb169dde41baaa6f1d16d0d1eb7b73651e89fd5e416ba743c0dcd635d52cb59f991947558d4a72328e5f818154abd7ade41ac",
          "sha256": "476e2f66991ef53fcb618f3b8fb1c5bbeca001460e031c6b08352685c36cb67f",
          "sha1": "8aff2e8b31e9fd88b5d3ed19f3fc8367a8b5ee2c",
          "md5": "3f66c24df5726647bd61691546df3ac7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-0.0.4.aar",
          "url": "designsystem-0.0.4.aar",
          "size": 2219307,
          "sha512": "b54fce52d9f7bb9d72f8ed1e0ffcb169dde41baaa6f1d16d0d1eb7b73651e89fd5e416ba743c0dcd635d52cb59f991947558d4a72328e5f818154abd7ade41ac",
          "sha256": "476e2f66991ef53fcb618f3b8fb1c5bbeca001460e031c6b08352685c36cb67f",
          "sha1": "8aff2e8b31e9fd88b5d3ed19f3fc8367a8b5ee2c",
          "md5": "3f66c24df5726647bd61691546df3ac7"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "designsystem-0.0.4-sources.jar",
          "url": "designsystem-0.0.4-sources.jar",
          "size": 186664,
          "sha512": "9614f78a9276a651881c828ce8ae937ebbee23c28375f83dc509a8d324f7cf931fa59c1b70c2317d883fb9adab803edef83d2dbc7d1a1eddef60a3ce2d8a2abb",
          "sha256": "cfd08e33faa323a3626d635b65e1106360d1745d99f43064ddd62c2781684cb0",
          "sha1": "7a8b1674526a6852fdd1566925868f6aa36f4a37",
          "md5": "f33add38e8818684de917f017fb8e814"
        }
      ]
    }
  ]
}
