{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface.doc",
    "module": "ui",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface.doc",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "domain",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "designsystem",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.0.aar",
          "url": "ui-1.0.0.aar",
          "size": 172597,
          "sha512": "1ffb3a73f511164aae31a036dc35291fc9745bdca767c747c0023ab85c6bd609bf55e1c397ea7d76c9b16d39046a7f27043941bd9b4cafedeabef2f82b2c4f4c",
          "sha256": "ee77157864fb3a126942681306562653d681c4319f2a41467afad802d27d81ed",
          "sha1": "753d3adb69886c13de1d92acb5c27eb38049621e",
          "md5": "829d97b5e42ed35210971bdbb3db77d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "data",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "domain",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "designsystem",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.0.aar",
          "url": "ui-1.0.0.aar",
          "size": 172597,
          "sha512": "1ffb3a73f511164aae31a036dc35291fc9745bdca767c747c0023ab85c6bd609bf55e1c397ea7d76c9b16d39046a7f27043941bd9b4cafedeabef2f82b2c4f4c",
          "sha256": "ee77157864fb3a126942681306562653d681c4319f2a41467afad802d27d81ed",
          "sha1": "753d3adb69886c13de1d92acb5c27eb38049621e",
          "md5": "829d97b5e42ed35210971bdbb3db77d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-1.0.0-sources.jar",
          "url": "ui-1.0.0-sources.jar",
          "size": 18251,
          "sha512": "35077d69c7f62028a876ce10fbfb29b8276005fc8ecb162b34a1a5e7686e833128e269621e6f86071111f80001d700c46893c0c13875322dff022988269eb2c6",
          "sha256": "e84080ddc3d094f4ebfff1c874cf3397681c9047d86f970e1815f494811ad32a",
          "sha1": "e45aaf20b4e86637a76a768dd2e81fb3d83f757b",
          "md5": "359a315a53079be7403008438a762f9d"
        }
      ]
    }
  ]
}
