{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "utils",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.4.aar",
          "url": "utils-0.0.4.aar",
          "size": 94737,
          "sha512": "ba5f46f4ab988d8a25b6407fa6a10c8e11239dc5c93068281b2a88c61332b860e1cad8f0e26dc0fe1276a615ec20e2d901b291a202b277b8ef63db927e03073d",
          "sha256": "4c7f2e2f926637944cb4d2f988bc5294bd82fe9a67d4b8af81138cd805d6ab45",
          "sha1": "700944d513061235c375e1aa813b8effe5324c68",
          "md5": "58ec19c3e9a36a7b6375ca7fc835d4a9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.4.aar",
          "url": "utils-0.0.4.aar",
          "size": 94737,
          "sha512": "ba5f46f4ab988d8a25b6407fa6a10c8e11239dc5c93068281b2a88c61332b860e1cad8f0e26dc0fe1276a615ec20e2d901b291a202b277b8ef63db927e03073d",
          "sha256": "4c7f2e2f926637944cb4d2f988bc5294bd82fe9a67d4b8af81138cd805d6ab45",
          "sha1": "700944d513061235c375e1aa813b8effe5324c68",
          "md5": "58ec19c3e9a36a7b6375ca7fc835d4a9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "utils-0.0.4-sources.jar",
          "url": "utils-0.0.4-sources.jar",
          "size": 60925,
          "sha512": "00f9713e51c86f630bf7df5673644aabb53150be20697850d51e962e77ad04f12c642a8bbb9e9a925a59dd3ed818378df036f23fa8307114d99060f0679636b5",
          "sha256": "5b19ac8848cae3791bc30b9111538d93762bfa11a939a7dadb9ff8ea018cfc27",
          "sha1": "7c40147f1ce17c1f4c9c8f6738cd93d351319df4",
          "md5": "c4d12e86bad92adcaeabc0d30a802aea"
        }
      ]
    }
  ]
}
