{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "logging",
    "version": "1.0.0-snapshot-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.0-snapshot-3.aar",
          "url": "logging-1.0.0-snapshot-3.aar",
          "size": 65522,
          "sha512": "68455e9238609f14a1777f98fdc759b1a32fa8688e92f29e2fa0f18a01dd9998aaa26231157301225c7b0e9a76a132f4e7eb9eba51ae467fe3fab2ada632ce32",
          "sha256": "2336bf8da29a43008fa0d317924c2b6dabaa4727ef55bb989229ca4ebb593250",
          "sha1": "0f2fe8c1875574372ac331378eefba23d6ceefb7",
          "md5": "76209ad9666f94ba4b16fe303c922c3d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.0.0-snapshot-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.0.0-snapshot-3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.0.0-snapshot-3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.0-snapshot-3.aar",
          "url": "logging-1.0.0-snapshot-3.aar",
          "size": 65522,
          "sha512": "68455e9238609f14a1777f98fdc759b1a32fa8688e92f29e2fa0f18a01dd9998aaa26231157301225c7b0e9a76a132f4e7eb9eba51ae467fe3fab2ada632ce32",
          "sha256": "2336bf8da29a43008fa0d317924c2b6dabaa4727ef55bb989229ca4ebb593250",
          "sha1": "0f2fe8c1875574372ac331378eefba23d6ceefb7",
          "md5": "76209ad9666f94ba4b16fe303c922c3d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-1.0.0-snapshot-3-sources.jar",
          "url": "logging-1.0.0-snapshot-3-sources.jar",
          "size": 27203,
          "sha512": "9760a8985065b3f925037d8230107238f9dcde6933c8ea8e98611f2ae752756d7a840f304ca52ec022fe6909a14034de639252b176bf3cc26f33ad3606443c74",
          "sha256": "4c7c439a7d4f8effb96bf55ebd026b31aaae866eb432b4c447b261fe25901897",
          "sha1": "58e3188eb1d9801324ec04812285b6a93da3c792",
          "md5": "34220b4ff47b6c8d0354c1dc19b86aad"
        }
      ]
    }
  ]
}
