{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "logging",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.4.aar",
          "url": "logging-0.0.4.aar",
          "size": 85825,
          "sha512": "54e6739e9adba7507efd91c3e7d052180e3be6ffaaee1f8c06b4d7674d31356ff8efc0c1d591d801fcf19296c5d5713f8cb6fee7528b22c8f88df121e33c5e3e",
          "sha256": "d620b2f6b38a84a0d88abf4a8a4ee9bf5e18940e6c683388f10fadead1692ead",
          "sha1": "85c9ebbb09166a729ee7e649cf4b71da107b88cf",
          "md5": "a5ca2091fa3d997aac1041ff6f6c54b1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-0.0.4.aar",
          "url": "logging-0.0.4.aar",
          "size": 85825,
          "sha512": "54e6739e9adba7507efd91c3e7d052180e3be6ffaaee1f8c06b4d7674d31356ff8efc0c1d591d801fcf19296c5d5713f8cb6fee7528b22c8f88df121e33c5e3e",
          "sha256": "d620b2f6b38a84a0d88abf4a8a4ee9bf5e18940e6c683388f10fadead1692ead",
          "sha1": "85c9ebbb09166a729ee7e649cf4b71da107b88cf",
          "md5": "a5ca2091fa3d997aac1041ff6f6c54b1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "logging-0.0.4-sources.jar",
          "url": "logging-0.0.4-sources.jar",
          "size": 54414,
          "sha512": "6f8464e016f1f92dbbc8838e374d3d7f454d8a353b6204e6c948c10a4d116d51dc93a661ffcc26f02657b80e4bf39f18e659269f24c8a473465faacb82d96bfe",
          "sha256": "efed7da75145abf79de565e18593132eb86876366bc9413de3e82e48a1f45566",
          "sha1": "5f663c9db9fd300f30212d943decb9de2ee5c00c",
          "md5": "2b078fabecbd1f6ce1857e468d5bd9a6"
        }
      ]
    }
  ]
}
