{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "logging",
    "version": "1.0.0-snapshot-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.0-snapshot-1.aar",
          "url": "logging-1.0.0-snapshot-1.aar",
          "size": 85555,
          "sha512": "fcabab68d7ae3d1edaf97ec656f648ef988f29e4b8ca040730dfb7c7bad7c10049920fd2ac0fc7f7442dad4b765a600d4257f5a3b68ee32b5cc0ae1ef613da85",
          "sha256": "6583ffd86d1319c4609fea7b9faaad3f2def6833946202cef7a4c5b64b7420be",
          "sha1": "22f457919c04c384d793d15fc73dd0093eae535f",
          "md5": "891a742b24aac3db606bd9bc3d87c473"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "1.0.0-snapshot-1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "1.0.0-snapshot-1"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "1.0.0-snapshot-1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "logging-1.0.0-snapshot-1.aar",
          "url": "logging-1.0.0-snapshot-1.aar",
          "size": 85555,
          "sha512": "fcabab68d7ae3d1edaf97ec656f648ef988f29e4b8ca040730dfb7c7bad7c10049920fd2ac0fc7f7442dad4b765a600d4257f5a3b68ee32b5cc0ae1ef613da85",
          "sha256": "6583ffd86d1319c4609fea7b9faaad3f2def6833946202cef7a4c5b64b7420be",
          "sha1": "22f457919c04c384d793d15fc73dd0093eae535f",
          "md5": "891a742b24aac3db606bd9bc3d87c473"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-1.0.0-snapshot-1-sources.jar",
          "url": "logging-1.0.0-snapshot-1-sources.jar",
          "size": 27203,
          "sha512": "9760a8985065b3f925037d8230107238f9dcde6933c8ea8e98611f2ae752756d7a840f304ca52ec022fe6909a14034de639252b176bf3cc26f33ad3606443c74",
          "sha256": "4c7c439a7d4f8effb96bf55ebd026b31aaae866eb432b4c447b261fe25901897",
          "sha1": "58e3188eb1d9801324ec04812285b6a93da3c792",
          "md5": "34220b4ff47b6c8d0354c1dc19b86aad"
        }
      ]
    }
  ]
}
