{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface.doc",
    "module": "designsystem",
    "version": "1.0.2-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface.doc",
          "module": "multimedia",
          "version": {
            "requires": "1.0.2-snapshot"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.2-snapshot.aar",
          "url": "designsystem-1.0.2-snapshot.aar",
          "size": 2088200,
          "sha512": "6eb2936285b1d480282faa1c8f6486bb4abf9be52f5a5629bb4f2d93f00b861cbffae3171cac66991d018e92d1064f79d7efca3ad4cdd4bf61009bb4f5a20dfd",
          "sha256": "d392e8175d9f08db4b8586e0ae965d32faeda9573234d903cc2dd827eccb8f0a",
          "sha1": "b92b2f2bc439a4881764f1b175df9af1c49dba63",
          "md5": "e106c1dc1352545de89c4f8feee6d966"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "multimedia",
          "version": {
            "requires": "1.0.2-snapshot"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.2-snapshot.aar",
          "url": "designsystem-1.0.2-snapshot.aar",
          "size": 2088200,
          "sha512": "6eb2936285b1d480282faa1c8f6486bb4abf9be52f5a5629bb4f2d93f00b861cbffae3171cac66991d018e92d1064f79d7efca3ad4cdd4bf61009bb4f5a20dfd",
          "sha256": "d392e8175d9f08db4b8586e0ae965d32faeda9573234d903cc2dd827eccb8f0a",
          "sha1": "b92b2f2bc439a4881764f1b175df9af1c49dba63",
          "md5": "e106c1dc1352545de89c4f8feee6d966"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.0.2-snapshot-sources.jar",
          "url": "designsystem-1.0.2-snapshot-sources.jar",
          "size": 72930,
          "sha512": "b50134ad8299b359a43a328eb3b5c4ee80188eb9b57671cc6dd0f1272de5c3bbaa43a36e679b126391a4954410201afea41cf50524c0023aa50c0f9c008d0f49",
          "sha256": "a55d92793abcc2ed6505141e3ea30d98bae5761d73149440748f5dc5820e0ec8",
          "sha1": "ef56742a798d35e72ed7066ed7f81f08c4e8351c",
          "md5": "28470f2c5acccb81a250fccb6ad2d5df"
        }
      ]
    }
  ]
}
