{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface.doc",
    "module": "designsystem",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface.doc",
          "module": "multimedia",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.1.aar",
          "url": "designsystem-1.0.1.aar",
          "size": 2062575,
          "sha512": "d2c35cf801c2fcb49d4a6866ac70ea1967ae3b714c937fda2fee37db26c2598e978f5c1bb9dcd41da6f1214baf7356e02834002f9e91d4ec16c1dd3a085d67df",
          "sha256": "f7f1ea2e93d9d1f362c056198bb894a5a61deecbf0a55186140148a5df56ac4e",
          "sha1": "579a188507d09a793e7cb4d23e292d11d51ddcbc",
          "md5": "ca80384aa824503ba3eb13d9207c4a61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.certiface.doc",
          "module": "multimedia",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.1.aar",
          "url": "designsystem-1.0.1.aar",
          "size": 2062575,
          "sha512": "d2c35cf801c2fcb49d4a6866ac70ea1967ae3b714c937fda2fee37db26c2598e978f5c1bb9dcd41da6f1214baf7356e02834002f9e91d4ec16c1dd3a085d67df",
          "sha256": "f7f1ea2e93d9d1f362c056198bb894a5a61deecbf0a55186140148a5df56ac4e",
          "sha1": "579a188507d09a793e7cb4d23e292d11d51ddcbc",
          "md5": "ca80384aa824503ba3eb13d9207c4a61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.0.1-sources.jar",
          "url": "designsystem-1.0.1-sources.jar",
          "size": 68110,
          "sha512": "27f8f488edf16eddbaeeaa0cec0e81dae3375fcdcec1f38f02f30bf21a70146b384ce862aab5e15bc8d96b4c65bb47ecc58c1a48153b127d8e50a2dbb79a98b4",
          "sha256": "29bef1a3cd16178d190256080e268f34edda58c302313d8a23687b6aeb822146",
          "sha1": "a03b92da97ba133ba81ac8abfe1ec8af4deedee3",
          "md5": "f1248952d0836347ff71f18accd5e239"
        }
      ]
    }
  ]
}
