{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "designsystem",
    "version": "1.0.0-snapshot-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-1.aar",
          "url": "designsystem-1.0.0-snapshot-1.aar",
          "size": 2144223,
          "sha512": "995e532ed8f91abf5cd090aaf48cc351f183fb00dffeed836ef9012513b68c6872cda33e8311b572057912c6d165d3ea6c35450de7ad4c5dec7462800d763251",
          "sha256": "71c1c25daaef0f17c39c01fb9374f5f0ab341b3e1874fda3f4f8c1ff0c15216f",
          "sha1": "33d04772a71cd63cbfe936016a35451db1e6fe0e",
          "md5": "f74a4b8391aff2cb7664fc1f3bb5a29e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-1.aar",
          "url": "designsystem-1.0.0-snapshot-1.aar",
          "size": 2144223,
          "sha512": "995e532ed8f91abf5cd090aaf48cc351f183fb00dffeed836ef9012513b68c6872cda33e8311b572057912c6d165d3ea6c35450de7ad4c5dec7462800d763251",
          "sha256": "71c1c25daaef0f17c39c01fb9374f5f0ab341b3e1874fda3f4f8c1ff0c15216f",
          "sha1": "33d04772a71cd63cbfe936016a35451db1e6fe0e",
          "md5": "f74a4b8391aff2cb7664fc1f3bb5a29e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "designsystem-1.0.0-snapshot-1-sources.jar",
          "url": "designsystem-1.0.0-snapshot-1-sources.jar",
          "size": 64546,
          "sha512": "d4a242e68ecddb3275f62f072dc01e90e0eb78887f568b69749542d9203d7b5c1f32396f9a69235f1f0d361f00c142fd67bfde094de254800dfcf3fadaa477b0",
          "sha256": "ec1f077d62ec2219c6d2ce648c415320b9143c2bcbc34102a8fe5a96677efd5b",
          "sha1": "f85052bc775101456bdaf8e3d99de70a596061d0",
          "md5": "7a581964da6295e05162fb9738371775"
        }
      ]
    }
  ]
}
