{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "multimedia",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "multimedia-0.0.4.aar",
          "url": "multimedia-0.0.4.aar",
          "size": 66159,
          "sha512": "d3bad9aaa634f24327762fe5487e9031fcc3e3cd8f54cc4ae11aece4250516e8e2330374929a624fdfeb6ff8eab5765b0158fcd35de33bd095a0334dbdc72f3f",
          "sha256": "26213b217a51a347280aeca35d4b80996efeb0df9e58b0bc0d5146a5416135bb",
          "sha1": "1b82924a765fb033a5f9b2996822bdbc41961cfe",
          "md5": "5f3a5acdcb6016cbce7fb4901646aac4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "multimedia-0.0.4.aar",
          "url": "multimedia-0.0.4.aar",
          "size": 66159,
          "sha512": "d3bad9aaa634f24327762fe5487e9031fcc3e3cd8f54cc4ae11aece4250516e8e2330374929a624fdfeb6ff8eab5765b0158fcd35de33bd095a0334dbdc72f3f",
          "sha256": "26213b217a51a347280aeca35d4b80996efeb0df9e58b0bc0d5146a5416135bb",
          "sha1": "1b82924a765fb033a5f9b2996822bdbc41961cfe",
          "md5": "5f3a5acdcb6016cbce7fb4901646aac4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "multimedia-0.0.4-sources.jar",
          "url": "multimedia-0.0.4-sources.jar",
          "size": 46610,
          "sha512": "cfbbfa79fd256cc4a6fcd54dbf89b429ef8a0985f1db11dccbf6a673079100758460731cbaceb8841ca91575d8457ffb3cec98a762c9fd88eddf61b39dccc79d",
          "sha256": "b50e31fb6b41bbf2c0b4d8597b7da72f0dd774c6e01e9b61fbfcfc0cd48f91dc",
          "sha1": "ec99e9fad995f5a11b33684dbfcfc4ff0b4659b2",
          "md5": "42e67bc211a033047e4ab25bc0b64fe1"
        }
      ]
    }
  ]
}
