{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface.doc",
    "module": "domain",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface.doc",
          "module": "designsystem",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.0.aar",
          "url": "domain-1.0.0.aar",
          "size": 43528,
          "sha512": "741863d1943bf0eaae072bef3504234364153a2b65720beeef0056f8c21d8344156883eb7fc116e337b4d04332303c2578c43c7e0989de18305792d97a456938",
          "sha256": "d20579ca4dc3790c34bdc3364b809a9eb01a66b276049305542a013e4543f3f1",
          "sha1": "726d17a3b8227adb0fba224eb223b5be15305955",
          "md5": "087cb2db708bb17e6e2bca209e3522f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "br.com.certiface.doc",
          "module": "designsystem",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.0.aar",
          "url": "domain-1.0.0.aar",
          "size": 43528,
          "sha512": "741863d1943bf0eaae072bef3504234364153a2b65720beeef0056f8c21d8344156883eb7fc116e337b4d04332303c2578c43c7e0989de18305792d97a456938",
          "sha256": "d20579ca4dc3790c34bdc3364b809a9eb01a66b276049305542a013e4543f3f1",
          "sha1": "726d17a3b8227adb0fba224eb223b5be15305955",
          "md5": "087cb2db708bb17e6e2bca209e3522f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.0.0-sources.jar",
          "url": "domain-1.0.0-sources.jar",
          "size": 11135,
          "sha512": "9a07d0713a45d3aa6996cab71aaff16a79004fe783b9aeaa64718309690259b62c9febf6131c11bd7155fd09a50171783de361f34c92da32716fe28e1f82fe50",
          "sha256": "4ebbae2d6ee691852bb41d7a2707530d1bffb126819aadc0430b7eb48efe8280",
          "sha1": "cd9c0046076ffe7f3d41d6a6d51904b1bd8af00a",
          "md5": "087e22f846c6bd0d9f4e9fc757a0fd8e"
        }
      ]
    }
  ]
}
