{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.0.0-snapshot-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.0.0-snapshot-3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.0-snapshot-3.aar",
          "url": "domain-1.0.0-snapshot-3.aar",
          "size": 42689,
          "sha512": "d8eb6e3a6a6e2510c18d0bbbb7a19b1c884bf29d03627abb72aa6e3ab7f053be042b6449a482be113e7e05d0839341e40350788e481df479c77969e6cab18482",
          "sha256": "b25518537b57ef81729f3303bb3a6ed9c1b65e3e8b70b2173a3a0d5d36c06214",
          "sha1": "a5da62693b924e7f99849d189f5b610bd9a2f68b",
          "md5": "7054eff7ed53c94d4a79b123baf13dbc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.0.0-snapshot-3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.0-snapshot-3.aar",
          "url": "domain-1.0.0-snapshot-3.aar",
          "size": 42689,
          "sha512": "d8eb6e3a6a6e2510c18d0bbbb7a19b1c884bf29d03627abb72aa6e3ab7f053be042b6449a482be113e7e05d0839341e40350788e481df479c77969e6cab18482",
          "sha256": "b25518537b57ef81729f3303bb3a6ed9c1b65e3e8b70b2173a3a0d5d36c06214",
          "sha1": "a5da62693b924e7f99849d189f5b610bd9a2f68b",
          "md5": "7054eff7ed53c94d4a79b123baf13dbc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.0.0-snapshot-3-sources.jar",
          "url": "domain-1.0.0-snapshot-3-sources.jar",
          "size": 11038,
          "sha512": "3c05e2e5b6fdd94bffeda863c37fa4d2841aefb3b229b6b781fd7f854a45cd800dfee72b09dccb36e7335bee700ab2e9b6c67358e7cf0e9bfae58daacc1608a2",
          "sha256": "6aa2d53ef02033689e816fe975b5707d7d4e7088f2229d16ea8e18b5b2cbae9d",
          "sha1": "c94101bd724227022f8d75dbb41889a874a7bde3",
          "md5": "a289a0dde4a8cdcd24f0200ec905f2fd"
        }
      ]
    }
  ]
}
