{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "network",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-0.0.2.aar",
          "url": "network-0.0.2.aar",
          "size": 37094,
          "sha512": "0c141611229e86b96f9cae99133c0b65f15c9fa2da6b44efa15bb6c5b48878f9855eceb63f13ae730b556dba61d5d611b8bd403e5d942754568b64753a6e0a69",
          "sha256": "bdf1a3ff24d82bb4e071fdcacd310b9be2110a0b75bcda651e03d484fc9b9648",
          "sha1": "ca5e4202ed1a7efb08c8574c6cb865bbb2b2b4e4",
          "md5": "7f55ee0878d55ae6f825e21740ff1913"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "network-0.0.2.aar",
          "url": "network-0.0.2.aar",
          "size": 37094,
          "sha512": "0c141611229e86b96f9cae99133c0b65f15c9fa2da6b44efa15bb6c5b48878f9855eceb63f13ae730b556dba61d5d611b8bd403e5d942754568b64753a6e0a69",
          "sha256": "bdf1a3ff24d82bb4e071fdcacd310b9be2110a0b75bcda651e03d484fc9b9648",
          "sha1": "ca5e4202ed1a7efb08c8574c6cb865bbb2b2b4e4",
          "md5": "7f55ee0878d55ae6f825e21740ff1913"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "network-0.0.2-sources.jar",
          "url": "network-0.0.2-sources.jar",
          "size": 31311,
          "sha512": "5b3996a17029407b56b4a7e172bf5055e0fc00225b184dd4086f90a3bea1d83d83805d72e4fa7d32d4386e327dfec746ce95529034cbfa740b068078bc5c3458",
          "sha256": "578ed3ec883b7f6865b0193acea223c7f8c297418c539e7b0f8ee41b1cbada17",
          "sha1": "a6434f04a5f0ca22e39e973264e43e639e889b32",
          "md5": "ef39732ec6df2229f783b0a5be00166a"
        }
      ]
    }
  ]
}
