{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "manager",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "ui",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "manager-0.0.3.aar",
          "url": "manager-0.0.3.aar",
          "size": 52111,
          "sha512": "f34ae20405a9096cef9909735da8154931eec2d590d7cd959e5cad84db9efc985258070229094628949f640918c168019d14a70c632541973a5f98d7202516d6",
          "sha256": "cf2c68dd9df385a0b188ed0c6d37ec8471a4d03c794eb7dd926bf64d3148f7e4",
          "sha1": "71323a7f47295a69a3d1e919bdc206638b627d84",
          "md5": "c8890769c93104fd10f33653c21ec899"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "data",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "ui",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "manager-0.0.3.aar",
          "url": "manager-0.0.3.aar",
          "size": 52111,
          "sha512": "f34ae20405a9096cef9909735da8154931eec2d590d7cd959e5cad84db9efc985258070229094628949f640918c168019d14a70c632541973a5f98d7202516d6",
          "sha256": "cf2c68dd9df385a0b188ed0c6d37ec8471a4d03c794eb7dd926bf64d3148f7e4",
          "sha1": "71323a7f47295a69a3d1e919bdc206638b627d84",
          "md5": "c8890769c93104fd10f33653c21ec899"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "manager-0.0.3-sources.jar",
          "url": "manager-0.0.3-sources.jar",
          "size": 43306,
          "sha512": "1c573fb8bb0c2c7ad0863632046deb23154deb48f23a5e0190ca1469a04a1a6c5bf809275454f5a86947c1a85a42b1ee3b9a2b799a85121a8e0f34451ac9d624",
          "sha256": "8d4d5c89dcb6eb62f7a970392a3c2832e9af7b2384777e1237abac7b76c48077",
          "sha1": "29cadfed3ee28ff6909114f12c804a37474c4f39",
          "md5": "7577c6f18776e86dfdf8dbaeeac29a95"
        }
      ]
    }
  ]
}
