{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "1.0.0-snapshot-7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.0.0-snapshot-7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.0-snapshot-7.aar",
          "url": "domain-1.0.0-snapshot-7.aar",
          "size": 44236,
          "sha512": "2abc76eb066abe1f7faf66ad337a452a8f58f1ccff7a428ec00b2321018bd881ae87c7d6279c4508759b2cc666744c89060fdb7f30fd085deb4b7396d9314995",
          "sha256": "b2c5956678ab398725a8da410b1b913726d30fa5c3ca5dd2dd3383061f5c9837",
          "sha1": "e40c92ceb9341ae58869113efc42d8609eeb415a",
          "md5": "52b5121f2f5ca8b3a54e93e1c51b0dd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "1.0.0-snapshot-7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-1.0.0-snapshot-7.aar",
          "url": "domain-1.0.0-snapshot-7.aar",
          "size": 44236,
          "sha512": "2abc76eb066abe1f7faf66ad337a452a8f58f1ccff7a428ec00b2321018bd881ae87c7d6279c4508759b2cc666744c89060fdb7f30fd085deb4b7396d9314995",
          "sha256": "b2c5956678ab398725a8da410b1b913726d30fa5c3ca5dd2dd3383061f5c9837",
          "sha1": "e40c92ceb9341ae58869113efc42d8609eeb415a",
          "md5": "52b5121f2f5ca8b3a54e93e1c51b0dd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "domain-1.0.0-snapshot-7-sources.jar",
          "url": "domain-1.0.0-snapshot-7-sources.jar",
          "size": 11229,
          "sha512": "e607e664a22d8dc64f5a4c8dce62f44a7b72a42a81e835694e38b2c20e3f19e56567da2f9b6f107674d386b769690c26d2a525cbbee75fa7de96cf6fd034f767",
          "sha256": "f59f9c39dd52f3ef5ec96a090a5bf2b224b2aeeeb7e59c13ea9054298fe07583",
          "sha1": "514906caf2b946835286da43b82e11be763a20e1",
          "md5": "c4c5b9ea6f9a2b8f8970ac39290dfc5a"
        }
      ]
    }
  ]
}
