{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "manager",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "ui",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "manager-0.0.4.aar",
          "url": "manager-0.0.4.aar",
          "size": 51719,
          "sha512": "3dff511f51d824cbd00e9776500133a6a563032bf049b119238a569088694ff75aabb3e07b4709bfdfcd7ffccd48b4cf19950dcbb134902a9cb7d8c374c815f0",
          "sha256": "f29cc0ce4abf0177a67e4a50905041ca05c421a611f3765f5c81a56dd664c505",
          "sha1": "a103be4f5c81d726cbf3327b1c8d4820959096ee",
          "md5": "1a9cd3881fd5eb5061e447f5089e7513"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "data",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "utils",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "logging",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "domain",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "network",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "br.com.certiface",
          "module": "ui",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "manager-0.0.4.aar",
          "url": "manager-0.0.4.aar",
          "size": 51719,
          "sha512": "3dff511f51d824cbd00e9776500133a6a563032bf049b119238a569088694ff75aabb3e07b4709bfdfcd7ffccd48b4cf19950dcbb134902a9cb7d8c374c815f0",
          "sha256": "f29cc0ce4abf0177a67e4a50905041ca05c421a611f3765f5c81a56dd664c505",
          "sha1": "a103be4f5c81d726cbf3327b1c8d4820959096ee",
          "md5": "1a9cd3881fd5eb5061e447f5089e7513"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "manager-0.0.4-sources.jar",
          "url": "manager-0.0.4-sources.jar",
          "size": 42898,
          "sha512": "64d53139b28b03045b1eb712b0a9d0ea41927bb18caeedbcc3cc7c82f837c3fb7d132053f58666e16208f66b9b575f64c58297d71a73a8ab0a3b5e6a99df8049",
          "sha256": "d4b0e3b8bc1ee46b94e507b6982d897d8cccf042e550d12d3e96faaf56a065cb",
          "sha1": "b6d43f10d98954e6b6817abcb8f08bfef404c22c",
          "md5": "af41cab23d67cc142563aa8e7235441d"
        }
      ]
    }
  ]
}
