{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "multimedia",
    "version": "1.0.0-snapshot-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "multimedia-1.0.0-snapshot-3.aar",
          "url": "multimedia-1.0.0-snapshot-3.aar",
          "size": 48731,
          "sha512": "da23bec910901823b35500d2555b332bdbf8403a96463aec6e560b7478e1d81d3dca2a0ec0fff533fd0733cde39c3c9baf4c9ace4a0f65315b6ef05de48f9714",
          "sha256": "f899ff7b1f3a911d4f6f5a4dffb45712423ed785e338add22e6f8bbc3a4d9f9a",
          "sha1": "d67521c80835738292353386e116656198e02f9a",
          "md5": "a1b42430f78548213165f577dc28c545"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "multimedia-1.0.0-snapshot-3.aar",
          "url": "multimedia-1.0.0-snapshot-3.aar",
          "size": 48731,
          "sha512": "da23bec910901823b35500d2555b332bdbf8403a96463aec6e560b7478e1d81d3dca2a0ec0fff533fd0733cde39c3c9baf4c9ace4a0f65315b6ef05de48f9714",
          "sha256": "f899ff7b1f3a911d4f6f5a4dffb45712423ed785e338add22e6f8bbc3a4d9f9a",
          "sha1": "d67521c80835738292353386e116656198e02f9a",
          "md5": "a1b42430f78548213165f577dc28c545"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multimedia-1.0.0-snapshot-3-sources.jar",
          "url": "multimedia-1.0.0-snapshot-3-sources.jar",
          "size": 17212,
          "sha512": "68deb52a33fecdb2e9f25ceb58f502fa43c63e4dfa698b690a98522aa9dbf6b4c948affdc44c00d88d364dd40a56ec7ccf6d98256763fcfe9e9a0c49d3781a15",
          "sha256": "0a1e7058a668843c6f282e38982ea6e368505de1a034409de47967c2827a467f",
          "sha1": "e7caf3f2a8f78850be9d04b41f30c3816775d627",
          "md5": "30ea1eba8bc44d9b09d5b22cfe8d1d4c"
        }
      ]
    }
  ]
}
