{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.certiface",
    "module": "domain",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.4.aar",
          "url": "domain-0.0.4.aar",
          "size": 40836,
          "sha512": "6176b7811fa5c0ce0d63216d99630411c46e21483cb21281a523cef13d87d2330c35605d8458b4ee81c8522fc2496b36d450dd5cfbbd16f2de1113f6ab648b48",
          "sha256": "8cd33899efe5a41da185cd8ebfae46848c3df1f4734b714545db6b1871a460cf",
          "sha1": "aac3cb522bf3f8b3d42e2fadc3898aee4de8aef7",
          "md5": "311082b91bf5f20e7aece124d3b72b1d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "br.com.certiface",
          "module": "designsystem",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "domain-0.0.4.aar",
          "url": "domain-0.0.4.aar",
          "size": 40836,
          "sha512": "6176b7811fa5c0ce0d63216d99630411c46e21483cb21281a523cef13d87d2330c35605d8458b4ee81c8522fc2496b36d450dd5cfbbd16f2de1113f6ab648b48",
          "sha256": "8cd33899efe5a41da185cd8ebfae46848c3df1f4734b714545db6b1871a460cf",
          "sha1": "aac3cb522bf3f8b3d42e2fadc3898aee4de8aef7",
          "md5": "311082b91bf5f20e7aece124d3b72b1d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "domain-0.0.4-sources.jar",
          "url": "domain-0.0.4-sources.jar",
          "size": 28118,
          "sha512": "a9fbadc9ce0f31d4422644cdf76dc868f68eee3a6f9106a52ff56f0bef389b87221e165d2f9a488d2b6cf195407445430ee49446433da17561285911845e6040",
          "sha256": "2bdb6ac02dd3eab573108c14f0dec9e5ab0f83143936e0a06f7b8647c5b8cf13",
          "sha1": "00bbf6f36caec2b8c565c84bad7a645ace497519",
          "md5": "a74de419073bac6042fb35778d1df853"
        }
      ]
    }
  ]
}
